# docker-compose.yml
version: '3.8'

services:
  # Node.js/Express service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app 
      - /app/node_modules

    ports:
      - '${PORT}:${PORT}'
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo 
    restart: unless-stopped
  # MongoDB service
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    
    ports:
      - '27017:27017' 
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped
volumes:
  mongo-data:
